### ISSUE TITLE
Is this ready for Mobile Safari?

### ISSUE THREAD

**Issue by nathancarter** [ebidel/idb.filesystem.js#33]
I've heard of the [problems in Mobile Safari's IndexedDB implementation](http://www.raymondcamden.com/2014/9/25/IndexedDB-on-iOS-8--Broken-Bad), and seen [this other Mobile Safari issue in this repository](https://github.com/ebidel/idb.filesystem.js/issues/30).  For those reasons, I ask the question in the title of this issue.

If the answer is "yes," perhaps this issue can be closed with just a clarification of *how* the troubles mentioned at the two links above don't get in the way.

But if the answer is "no," then perhaps this issue becomes a question of whether there are bugs to fix or workarounds to implement or whatever.  (For instance, the first link mentions that there can't be keys in common across datastores on Mobile Safari.  Is there some way to ensure that doesn't happen when using idb.filesystem.js?  It seems that the keys are the full paths, correct?  So I just need to be sure that my *other* datastores don't use keys that look anything like full paths?)

**Comment by ebidel** [comment]
It's been a number of years since this issue was first open! Safari's implementation is in a much better spot now.
