### ISSUE TITLE
Polyfill no longer works in Firefox 36.0.4 for Mac

### ISSUE THREAD

**Issue by woranl** [ebidel/idb.filesystem.js#34]
When I launch the Basic Demo using Firefox 36.0.4 for Mac, I got the following errors from the Console:

"TypeError: idb_.db is null" on line 900
"UnknownError" on line 727

This Polyfill used to work fine, but recent Firefox seems to not like it.... any idea why?

**Comment by guypaskar** [comment]
There were many changes in indexedDB in ff 36. The api was changed (mainly dealing with persistent/temporary storage types)

**Comment by woranl** [comment]
It seems like there is something wrong with indexedDB.open in the FF 36.  I tried to launch other indexedDB demo online, and they all seem to fail at .open().

**Comment by guypaskar** [comment]
As I said , things have changed between ff 35 and ff 36... specifically in .open

Docs will be released soon.

**Comment by woranl** [comment]
This has nothing to do with API changes.  It is a Firefox 36 bug.  I tried renaming the storage folder in Firefox > Profiles to "storageBackup" and restart Firefox.  After restarting and relaunching the indexedDB app, Firefox rebuilt a new storage folder. This fixes the issue with indexedDB on Firefox 36.  Likely related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1110067

**Comment by havenchyk** [comment]
Same here for 36.0.4 on Windows 7.

**Comment by woranl** [comment]
@havenchyk, check this out https://bugzilla.mozilla.org/show_bug.cgi?id=1143003
You may be able to help pin point this bug

**Comment by ebidel** [comment]
The latest release should fix things. I didn't see any errors when testing but add to nuke by profile's storage folder because I often go back and forth between FF stable and nightly.

https://www.npmjs.com/package/idb.filesystem.js
