### ISSUE TITLE
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

### ISSUE THREAD

**Issue by lakshmanweb** [ebidel/idb.filesystem.js#37]
I am getting this error while implimentation.

If I changed it to navigator.webkitTemporaryStorage, then code will work with old browsers?
my application should be compatibly in chromium browser (raspberry).

Please suggest me.
Thanks.

**Comment by ebidel** [comment]
This was an issue with the playground demo not using the latest https://github.com/ebidel/filer.js. Not with the library itself. I've updated it.
