### ISSUE TITLE
TypeError: Type error in Safari

### ISSUE THREAD

**Issue by vheun** [ebidel/idb.filesystem.js#40]
Hi,
I am so happy that you guys do this work which allows us to use a filesystem API implementation outside of chrome.

When I try the basic demo in Safari, it gives me a "TypeError: Type error" for whenever I click on a newly uploaded file. Once I refresh the browser, the error disappears and I can open the file.

I tried to debug the error for a bit, but I am not sure where to start.
Do you have any idea?

Thank you

**Comment by ebidel** [comment]
Believe this should be fixed in https://github.com/ebidel/idb.filesystem.js/commit/0f4e014e4d205fd42dbc89be0a5f497a16546407. I'm not seeing any errors in Safari.
