### ISSUE TITLE
Fails when indexedDB is not supporting Blobs

### ISSUE THREAD

**Issue by SergejKasper** [ebidel/idb.filesystem.js#48]
When indexeddb is not supporting Blobs, the polyfill throws an error:
`PhantomJS 2.1.1 (Mac OS X 0.0.0) DataCloneError: DOM IDBDatabase Exception 25: The data being stored could not be cloned by the internal structured cloning algorithm.  `

It seems like the support-check in [src/idb.filesystem.js#L46](https://github.com/ebidel/idb.filesystem.js/blob/0795554233f13ea90cfd1b758bebaa343022a607/src/idb.filesystem.js#L46) is never executed

**Comment by ebidel** [comment]
Well that's no good! This was my bad in https://github.com/ebidel/idb.filesystem.js/commit/5fa21040fff256eed8a67d04c49ab546fc8a1def.

**Comment by ebidel** [comment]
Released 0.0.7. LMK if that doesn't work.
