### ISSUE TITLE
Doesn't work in Firefox in private browsing mode

### ISSUE THREAD

**Issue by foenyx** [ebidel/idb.filesystem.js#7]
Hello,
Seems like the indexedDB is logically disabled in private browsing mode (tried with Firefox 17).

https://developer.mozilla.org/en-US/docs/IndexedDB/Using_IndexedDB :
« Also, IndexedDB is completely disabled in the privacy modes of browsers (Private Browsing mode for Firefox and Incognito mode for Chrome).  »

It generates an error in the script:

<pre>
Error: InvalidStateError
File: http://html5-demos.appspot.com/static/filesystem/idb.filesystem.js/src/idb.filesystem.js
Line: 610
</pre>

→

``` js
var request = indexedDB.open(dbName.replace(':', '_')/*, 1 /*version*/);
```

which results in the web page as:

```
[object Event]
```

Maybe it's worth catching it and displaying a warning instead, don't you think ?

**Comment by ebidel** [comment]
This version of FF is very old. Closing :)
